# Generated by Django 3.2.22 on 2023-10-27 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_bdate', to='booking.booking')),
                ('booking_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_bnumber', to='booking.booking')),
                ('booking_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_btime', to='booking.booking')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_email', to=settings.AUTH_USER_MODEL)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_fname', to=settings.AUTH_USER_MODEL)),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_lname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
