# Generated by Django 3.2.22 on 2023-10-27 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('date_created', models.DateTimeField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_email', to=settings.AUTH_USER_MODEL)),
                ('first_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_fname', to=settings.AUTH_USER_MODEL)),
                ('last_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_lname', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
