# Generated by Django 3.2.22 on 2023-11-01 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20231031_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='delete',
        ),
    ]
