# Generated by Django 3.2.22 on 2023-10-26 16:09

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ingredients', models.CharField(max_length=150)),
                ('is_favourite', models.BooleanField(default=False)),
            ],
        ),
    ]
