# Generated by Django 3.2.22 on 2023-10-27 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
